function Chisep()
%% χ-separation Tool

% This tool is MATLAB-based software for reconstructing Quantitative Susceptibility Map (QSM) 
% and separating positive and negative susceptibility sources (χ-separation). 
% Separating paramagnetic (e.g., iron) and diamagnetic (e.g., myelin) susceptibility sources 
% co-existed in a voxel provides the distributions of two sources that QSM does not provides. 
% Magnetic susceptibility maps generated by QSM or χ-separation offer 
% important information for research or diagnosis. An inexperienced researcher (user) 
% can easily conduct QSM and χ-separation processing through the tool's user-friendly interface.

% χ-separation tool Beta version

% Contact E-mail: snu.list.software@gmail.com

% Reference
% H.-G. Shin, J. Lee, Y. H. Yun, S. H. Yoo, J. Jang, S.-H. Oh, Y. Nam, S. Jung, S. Kim, F. Masaki, W. 
% Kim, H. J. Choi, J. Lee. χ-separation: Magnetic susceptibility source separation toward iron and 
% myelin mapping in the brain. Neuroimage, 2021 Oct; 240:118371.

% χ-separation tool is powered by MEDI toolbox, STI Suite, and sepia.


%% EXCUETE Chi-separation Tool
HomeDirectory = fileparts(mfilename('fullpath'));
addpath(genpath(HomeDirectory));

ChisepTool(HomeDirectory);
end